/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "fullscreen.c"
#include "inplacerotate.c"
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tagallmon.c"
#include "tagothermonitor.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "winview.c"
#include "zoomswap.c"
#include "xrdb.c"
/* Layouts */
#include "layout_flextile-deluxe.c"
