/* Patches */
#include "autostart.h"
#include "cyclelayouts.h"
#include "dwmblocks.h"
#include "dwmc.h"
#include "ewmhtags.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "statuscmd.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tagallmon.h"
#include "tagswapmon.h"
#include "vanitygaps.h"
#include "winview.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "flextile-deluxe.h"
