/* Patches */
#include "autostart.c"
#include "cyclelayouts.c"
#include "dwmblocks.c"
#include "dwmc.c"
#include "ewmhtags.c"
#include "fullscreen.c"
#include "inplacerotate.c"
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#include "statuscmd.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tagallmon.c"
#include "tagothermonitor.c"
#include "tagswapmon.c"
#include "vanitygaps.c"
#include "winview.c"
#include "zoomswap.c"
#include "xrdb.c"
/* Layouts */
#include "flextile-deluxe.c"
