/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "autostart.h"
#include "cyclelayouts.h"
#include "dwmc.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tagallmon.h"
#include "tagothermonitor.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "winview.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
